name: Deployment
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI on runner
        run: npm install --global vercel@latest

      - name: Get vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Deploy project artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
